### PR TITLE
Updates to read.bismark(), mostly documentation

### PR DESCRIPTION
**Pull request by PeteHaitch**
Hi Kasper,

Following an email from a user, I'm proposing some updates to `read.bismark()`. Most of these are improvements to the documentation along with some minor internal updates. These are necessary due to multiple (albeit minor) changes to the file format returned by Bismark over different versions.

There are what look like a lot of differences in the code below, but most of these are cosmetic differences. Sorry about the noise.

The other changes:

- Added R.utils to IMPORTS. `data.table::fread()` can't work with gzip files directly. Henrik provides the useful isGzipped() and gunzip() functions in R.utils for simple handling of gzipped files. This dependency on R.utils could be removed but would add some annoying bookkeeping to handling gzip files with `data.table::fread()`.
- Updated example Bismark data, example in docs, and added some basic unittests.
- Added myself as a contributor in DESCRIPTION.

If you'd like I can make some minor modifications to `read.bsmooth()` and its dependencies to also use `data.table::fread()`; it blows the pants off everything else for reading data into R.

Cheers,
Pete

### CODE REVIEW

**Comment by kasperdanielhansen** [comment]
Hi Pete

Looks useful.  Could you investigate (briefly) whether readr::read_tsv from
Hadley (which is about 2x slower than fread) supports reading directly from
gzipped files?  One possible problem with gunzip() is that it get
decompressed to a temporary file.  These files can be big and on some
systems temporary files are size limited.

Reading this issue
  https://github.com/Rdatatable/data.table/issues/717
people also suggest the construction
  fread("zcat FILENAME.gz")
which does not make a temporary file, but assumes zcat is in the path on
the system.  This might be better from a resource perspective, but it makes
assumptions about the system.  Not sure what the best final solution is,
but if readr:read_tsv supports connections it is worth thinking about
(connections also allows you to read over the internet for example).

Kasper

**Comment by PeteHaitch** [comment]
Good points, I'll investigate readr::read_tsv() later today. Otherwise,
what do you think about allowing the user to pass a directory where files
are unzipped to (with tempdir() as default)?

**Comment by kasperdanielhansen** [comment]
I'm merging it.  The issues above would just lead to even more improvements; these patches are clearly better than what we currently have.

**Comment by PeteHaitch** [comment]
Cool, I'm investigating `readr::read_tsv()`. It definitely handles .gz, .bz2, .xz, and .zip as well as connections starting with http://, https://, ftp://, or ftps://

I'm running some benchmarks on versions of `bsseq::read.bismark()` with the `data.table::fread()` or the `readr::read_tsv()` backend using some mouse WGBS data, both plaintext and gzipped. I'll post the benchmarks here and, if worth doing, open a new pull request with additional changes.

**Comment by kasperdanielhansen** [comment]
I have looked into that and data.table is faster; this is also known.

However, if the speedup is minor (and I did not save careful benchmark
times) or perhaps even only 2x, one might consider using the more flexible
(it seems) read_tsv.  I did originally decide against it, but not
supporting gzip files is pretty bad.

Kasper

**Comment by PeteHaitch** [comment]
I forgot to post my follow-up. This benchmark uses whole-genome bisulfite-sequencing mouse data. Fairly low sequencing coverage, from memory. Plaintext versions are > 1GB, gzipped ~200 MB.

In summary:

- `data.table::fread()` is 3-5 times faster than `readr::read_tsv()` for the `.cov` and `cytosineReport` files when they are plaintext.
- `R.utils::gunzip + data.table::fread()` and `readr::read_tsv()` are almost identical for the `.cov` and `cytosineReport` files when they are gzipped.
- The running times are much more variable for `data.table::fread()` and `R.utils::gunzip() + data.table::fread()` than for `readr::read_tsv()`. I suspect that this is due to some caching black magic in both `data.table` and the system-level `gzip`.
- The downside of the `R.utils::gunzip() + data.table::fread()` method for handling gzipped files is that, as you note, it requires the creation of a temporary, unzipped version of the file. This is currently written to the value returned by `base::tempdir()`, which uses environment variables `TMPDIR`, `TMP` and `TEMP` or, if all else fails, `/tmp`. Alternatively, it could easily be added as an argument to the function so that the user can specify a different directory since these default locations may be too small on some systems.
- `readr::read_tsv()` can read natively from compressed files and connections.

The least-effort solution is to keep the `data.table::fread()` backend and note in the documentation how to specify the location of the temporary directory using environmental variables. I'm in favour of this approach unless the annoyance of temporarily unzipping files on some systems is bigger than I appreciate. 

Full details below the fold.

# `data.table::fread()` vs. `readr::read_tsv()`
Peter Hickey
2015-08-06  



A simple comparison of `data.table::fread()` vs. `readr::read_tsv()` on the Bismark `.cov` file and the Bismark `cytosineReport` file, both plaintext and gzipped, for the purposes of improving `bsseq::read.bismark()`.

__NB__: Subsequent runs of `data.table::fread()` (and `readr::read_tsv()`) on the same file are substantially faster than first (presumably some caching black magic going on there). Therefore I consider the median running time across five runs for each method.

## The `.cov` file

Functions to read in plaintext or gzipped `.cov` files using the `data.table::fread()` or `readr::read_tsv()` backend.


```r
fread_cov <- function(cov) {
  if (isGzipped(cov)) {
    cov <- gunzip(cov, 
                  temporary = TRUE,
                  overwrite = TRUE,
                  skip = FALSE,
                  remove = FALSE)
    # The unzipped version is removed otherwise each run will 
    on.exit(unlink(cov))
  }
  fread(input = cov,
        sep = "\t",
        header = FALSE,
        stringsAsFactors = FALSE,
        verbose = FALSE,
        select = c(1L, 2L, 5L, 6L),
        showProgress = FALSE)
}

# Annoyingly can't suppress all the output of readr::read_tsv() even when 
# progress = FALSE (see https://github.com/hadley/readr/pull/156)
read_tsv_cov <- function(cov) {
  read_tsv(file = cov,
           col_names = FALSE,
           col_types = "ci__ii",
           progress = FALSE)
}
```

### Plaintext


```r
cov <- "~/Desktop/tmp/DM_E6.5_epiblast_1.bismark.cov"
microbenchmark(fread_cov(cov = cov), read_tsv_cov(cov = cov), times = 5)
```

```
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
```

```
## Unit: seconds
##                     expr      min       lq     mean   median       uq
##     fread_cov(cov = cov) 10.19988 10.73929 14.43230 10.82330 12.00594
##  read_tsv_cov(cov = cov) 34.49449 35.04294 35.73532 35.46478 35.56543
##       max neval
##  28.39310     5
##  38.10897     5
```

### Gzipped


```r
covgz <- "~/Desktop/tmp/DM_E6.5_epiblast_1.bismark.cov.gz"
microbenchmark(fread_cov(covgz), read_tsv_cov(covgz), times = 5)
```

```
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
## 
|================================================================================| 100% 1216 MB
```

```
## Unit: seconds
##                 expr     min      lq     mean   median       uq       max
##     fread_cov(covgz) 36.1918 41.7421 67.07625 44.89138 74.10149 138.45448
##  read_tsv_cov(covgz) 44.9639 45.3021 46.08661 45.33961 46.64654  48.18091
##  neval
##      5
##      5
```

## The `cytosineReport` file

Functions to read in plaintext or gzipped `cytosineReport` files using the `data.table::fread()` or `readr::read_tsv()` backend.


```r
fread_cr <- function(cr) {
  if (isGzipped(cr)) {
    cr <- gunzip(cr, 
                 temporary = TRUE,
                 overwrite = TRUE,
                 remove = FALSE)
  }
  fread(input = cr,
        sep = "\t",
        header = FALSE,
        stringsAsFactors = FALSE,
        verbose = FALSE,
        select = c(1L, 2L, 3L, 4L, 5L))
}

read_tsv_cr <- function(cr) {
  read_tsv(file = cr,
           col_names = FALSE,
           col_types = "cicii__",
           progress = FALSE)
}
```

### Plaintext


```r
cr <- "~/Desktop/tmp/DM_E6.5_epiblast_1.bismark.cytosineReport"
microbenchmark(fread_cr(cr), read_tsv_cr(cr), times = 5)
```

```
## 
Read 0.0% of 43816016 rows
Read 12.2% of 43816016 rows
Read 24.4% of 43816016 rows
Read 36.6% of 43816016 rows
Read 48.8% of 43816016 rows
Read 61.1% of 43816016 rows
Read 73.5% of 43816016 rows
Read 86.0% of 43816016 rows
Read 98.4% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:12
## 
Read 0.0% of 43816016 rows
Read 12.1% of 43816016 rows
Read 24.2% of 43816016 rows
Read 36.4% of 43816016 rows
Read 48.5% of 43816016 rows
Read 60.5% of 43816016 rows
Read 72.7% of 43816016 rows
Read 85.0% of 43816016 rows
Read 97.0% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:11
## 
Read 0.0% of 43816016 rows
Read 12.2% of 43816016 rows
Read 24.7% of 43816016 rows
Read 37.4% of 43816016 rows
Read 49.7% of 43816016 rows
Read 62.2% of 43816016 rows
Read 74.4% of 43816016 rows
Read 86.4% of 43816016 rows
Read 98.5% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:12
## 
|================================================================================| 100% 1041 MB
## 
|================================================================================| 100% 1041 MB
## 
|================================================================================| 100% 1041 MB
## 
|================================================================================| 100% 1041 MB
## 
|================================================================================| 100% 1041 MB
## 
Read 0.0% of 43816016 rows
Read 10.5% of 43816016 rows
Read 19.9% of 43816016 rows
Read 29.5% of 43816016 rows
Read 39.3% of 43816016 rows
Read 50.7% of 43816016 rows
Read 62.6% of 43816016 rows
Read 74.4% of 43816016 rows
Read 86.1% of 43816016 rows
Read 97.9% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:14
## 
Read 0.0% of 43816016 rows
Read 11.5% of 43816016 rows
Read 23.8% of 43816016 rows
Read 36.1% of 43816016 rows
Read 48.5% of 43816016 rows
Read 60.8% of 43816016 rows
Read 73.2% of 43816016 rows
Read 85.5% of 43816016 rows
Read 98.2% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:11
```

```
## Unit: seconds
##             expr      min       lq     mean   median       uq      max
##     fread_cr(cr) 11.11733 11.24989 13.96167 11.32916 14.00607 22.10589
##  read_tsv_cr(cr) 41.00904 53.84638 53.28282 56.89935 57.06707 57.59226
##  neval
##      5
##      5
```

### Gzipped


```r
crgz <- "~/Desktop/tmp/DM_E6.5_epiblast_1.bismark.cytosineReport.gz"
microbenchmark(fread_cr(crgz), read_tsv_cr(crgz), times = 5)
```

```
## 
|================================================================================| 100% 1041 MB
## 
Read 0.0% of 43816016 rows
Read 11.3% of 43816016 rows
Read 23.5% of 43816016 rows
Read 35.5% of 43816016 rows
Read 47.6% of 43816016 rows
Read 59.6% of 43816016 rows
Read 71.4% of 43816016 rows
Read 83.6% of 43816016 rows
Read 95.9% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:13
## 
|================================================================================| 100% 1041 MB
## 
Read 0.0% of 43816016 rows
Read 12.4% of 43816016 rows
Read 23.8% of 43816016 rows
Read 34.9% of 43816016 rows
Read 46.6% of 43816016 rows
Read 55.9% of 43816016 rows
Read 64.6% of 43816016 rows
Read 75.1% of 43816016 rows
Read 85.7% of 43816016 rows
Read 96.3% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:13
## 
Read 0.0% of 43816016 rows
Read 11.9% of 43816016 rows
Read 23.3% of 43816016 rows
Read 34.9% of 43816016 rows
Read 45.9% of 43816016 rows
Read 57.7% of 43816016 rows
Read 69.5% of 43816016 rows
Read 81.4% of 43816016 rows
Read 93.3% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:13
## 
|================================================================================| 100% 1041 MB
## 
|================================================================================| 100% 1041 MB
## 
Read 0.0% of 43816016 rows
Read 12.1% of 43816016 rows
Read 24.2% of 43816016 rows
Read 36.5% of 43816016 rows
Read 48.9% of 43816016 rows
Read 61.2% of 43816016 rows
Read 73.4% of 43816016 rows
Read 85.7% of 43816016 rows
Read 97.7% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:12
## 
|================================================================================| 100% 1041 MB
## 
Read 0.0% of 43816016 rows
Read 11.8% of 43816016 rows
Read 23.4% of 43816016 rows
Read 35.4% of 43816016 rows
Read 47.5% of 43816016 rows
Read 59.6% of 43816016 rows
Read 71.8% of 43816016 rows
Read 84.1% of 43816016 rows
Read 96.7% of 43816016 rows
Read 43816016 rows and 5 (of 7) columns from 1.017 GB file in 00:00:12
```

```
## Unit: seconds
##               expr      min       lq     mean   median       uq      max
##     fread_cr(crgz) 46.94095 48.67389 68.14064 66.27298 78.82528 99.99010
##  read_tsv_cr(crgz) 63.56804 67.72512 68.63163 67.73269 69.49443 74.63788
##  neval
##      5
##      5
```

## Session Info


```r
sessionInfo()
```

```
## R version 3.2.1 (2015-06-18)
## Platform: x86_64-apple-darwin13.4.0 (64-bit)
## Running under: OS X 10.10.4 (Yosemite)
## 
## locale:
## [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] microbenchmark_1.4-2 R.utils_2.1.0        R.oo_1.19.0         
## [4] R.methodsS3_1.7.0    readr_0.1.1          data.table_1.9.4    
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.0      knitr_1.10.5     magrittr_1.5     MASS_7.3-43     
##  [5] munsell_0.4.2    colorspace_1.2-6 stringr_1.0.0    plyr_1.8.3      
##  [9] tools_3.2.1      grid_3.2.1       gtable_0.1.2     htmltools_0.2.6 
## [13] yaml_2.1.13      digest_0.6.8     reshape2_1.4.1   ggplot2_1.0.1   
## [17] formatR_1.2      evaluate_0.7     rmarkdown_0.7    stringi_0.5-5   
## [21] scales_0.2.5     chron_2.3-47     proto_0.3-10
```

**Pull request merged**
